### ISSUE TITLE
help

### ISSUE THREAD

**Issue by hubeiluotian** [MToquebiau/Joint-Intrinsic-Motivation#2]
Hello, thank you for providing the code. Thank you for your hard work, but when I was running the code, I found that RND and E3
B can run, but when I run novel, it will display 'killed', and I cannot find the problem with novel. Can you provide some help? Thank you!

**Comment by Maxtoq** [comment]
Hi, sure. 
It works for me, so can you provide the error message you got to help us figure it out ? 
Thanks

**Comment by hubeiluotian** [comment]
![N%D6H9E _`M3~0`SKNKZ C6](https://github.com/MToquebiau/Joint-Intrinsic-Motivation/assets/116795745/85b00a7c-292c-49f6-a723-b4434ee4a826)
The error message shows' killed ', which may be due to the process using resources beyond the system's available memory. If you can run novel, it may be due to an issue with my memory settings. Although I also encountered a' killed 'issue while running novel on the server, I will try to find the problem myself. Thank you for your help!

**Comment by Maxtoq** [comment]
Yes, it looks like it's a memory issue. The problem is not from the code. I don't know why you would get this from NovelD and not RND.

**Comment by hubeiluotian** [comment]
Hello, I'm sorry to bother you again,The first question I need to ask is: rnd.train，whose shape of input is dim=(episode_length,  batch_size, state_dim).
![ROFFXE(2ERF W$1AH 1EP50](https://github.com/MToquebiau/Joint-Intrinsic-Motivation/assets/116795745/9b14fcc7-9012-4232-bf75-b3ea09d0e4d1)
while the input shape of the target network is dim=(batch_size, input_dim)
![UF( ZU3YUGDL HB3)C9P_ZR](https://github.com/MToquebiau/Joint-Intrinsic-Motivation/assets/116795745/3956ea5e-a51d-4b71-9049-d569d5f11880)
![TXPPD9`51{W5BI9VYFO)4BC](https://github.com/MToquebiau/Joint-Intrinsic-Motivation/assets/116795745/654d63e1-f21c-4b97-a72e-f2e6ccfc7ad9)
The second place is, I know that in e3b, the shape of input you have here is dim=(episode_length, batch_size, state_dim)., but the shape of inpout I want now is dim=(batch_size, state_dim). Can I still make the code run successfully through some operations here?Can you give me some suggestions? Thank you very much！
![)17IJ)X~8OC0)FRXDNKWLL2](https://github.com/MToquebiau/Joint-Intrinsic-Motivation/assets/116795745/d6e12ddd-36eb-4b0d-88b1-07a211c40027)

**Comment by hubeiluotian** [comment]
I seem to have found a solution to the problem, thank you all the same!

**Comment by Maxtoq** [comment]
Okay, good. 
It's possible that some comments are not totally accurate, I should check and modify them if needed. 
However, the training of RND (or other models with only MLPs in them) would work with either dim=(episode_length, batch_size, state_dim) or dim=(batch_size, state_dim) as input, I think.
